In [1]:
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import random
sns.set()

Lemos los archivos para lodas las aperturas

In [3]:
Data=[]
for i in range(8,16):
    Data.append(pd.read_csv('aper'+str(i)+'.data', sep=" ",names=['colum'+str(x) for x in range(0,17)]))

In [4]:
Data[0]

,colum0,colum1,colum2,colum3,colum4,colum5,colum6,colum7,colum8,colum9,colum10,colum11,colum12,colum13,colum14,colum15,colum16
0,1810.409,NaN,85.261,NaN,V,NaN,05:50:07.700,NaN,1.110027,NaN,1810.471,NaN,85.696,NaN,INDEF,NaN,INDEF
1,1784.453,NaN,39.124,NaN,V,NaN,05:50:07.700,NaN,1.110027,NaN,1784.258,NaN,39.739,NaN,18.440,NaN,0.054
2,1885.556,NaN,117.939,NaN,V,NaN,05:50:07.700,NaN,1.110027,NaN,1884.425,NaN,119.786,NaN,24.143,NaN,10.416
3,1760.695,NaN,19.691,NaN,V,NaN,05:50:07.700,NaN,1.110027,NaN,1760.321,NaN,20.090,NaN,16.646,NaN,0.013
4,1857.939,NaN,107.120,NaN,V,NaN,05:50:07.700,NaN,1.110027,NaN,1857.698,NaN,108.055,NaN,19.743,NaN,0.148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7692,177.906,NaN,2018.421,NaN,I,NaN,07:39:30.517,NaN,1.126838,NaN,180.178,NaN,2031.834,NaN,INDEF,NaN,INDEF
7693,113.260,NaN,1732.432,NaN,I,NaN,07:39:30.517,NaN,1.126838,NaN,113.131,NaN,1732.669,NaN,19.198,NaN,0.106
7694,99.871,NaN,1704.454,NaN,I,NaN,07:39:30.517,NaN,1.126838,NaN,100.016,NaN,1704.914,NaN,18.625,NaN,0.064
7695,95.465,NaN,1692.750,NaN,I,NaN,07:39:30.517,NaN,1.126838,NaN,94.472,NaN,1693.101,NaN,19.366,NaN,0.117
7696,1693.751,NaN,2024.092,NaN,I,NaN,07:39:30.517,NaN,1.126838,NaN,1693.863,NaN,2024.569,NaN,INDEF,NaN,INDEF

In [7]:
for i in range(len(Data)):
    for j in [1,3,5,7,9,11,13,15]:
        Data[i] = Data[i].drop('colum'+str(j), axis='columns')

KeyError: "['colum1'] not found in axis"

In [ ]:
Data

In [ ]:
Data[1]
len(Data)

In [ ]:
for i in range(0,13):
    Data[i].rename(columns={'colum'+str(0):'XINIT','colum'+str(2):'YINIT','colum'+str(4):'IFILTER',
                        'colum'+str(6):'OTIME','colum'+str(8):'XAIRMASS','colum'+str(10):'XCENTER'
                        ,'colum'+str(12):'YCENTER','colum'+str(14):'MAG','colum'+str(16):'MERR'}, inplace=True)

In [ ]:
suma = 8
for data in Data:
    data['apertura'] = suma 
    suma += 1

In [ ]:
datos = range(0,12)
aperturas = range(8,21)
alt.Chart(Data[0]).mark_point()

In [ ]:
"""for i in datos:
    alt.Chart(Data[i]).mark_point()"""

In [ ]:

"""
alt.Chart(Data[i for i in range(0,12)]).mark_point().encode(
    x = 'apertura',
    y = 'MAG'
)"""

In [ ]:
"""alt.Chart(Data[0]).mark_point(filled=True).encode(
    alt.X('XCENTER'),
    alt.Y('MAG'),
    color = 'IFILTER'
)"""

In [ ]:
"""pd.plotting.scatter_matrix(Data[0], figsize=(15,15))
plt.show()"""

In [ ]:
"""for i in datos:
    pd.plotting.scatter_matrix(Data[i], figsize=(10,10))
    plt.show()"""

In [ ]:
Data

In [ ]:
datos_escogidos = [random.randint(0,1420) for i in range(0,50)]
#datos_escogidos = [1000]
df_grafica = pd.DataFrame()
datos_escogidos

In [ ]:

df_grafica['magnitude'] =  [datos['MAG'][i] for datos in Data for i in datos_escogidos]
df_grafica['apertur'] =  [datos['apertura'][i] for datos in Data for i in datos_escogidos]
df_grafica['error_mag'] =  [datos['MERR'][i] for datos in Data for i in datos_escogidos]
df_grafica['filtro'] =  [datos['IFILTER'][i] for datos in Data for i in datos_escogidos]
df_grafica['number'] =  [datos.index[i] for datos in Data for i in datos_escogidos]

In [ ]:
df_grafica

In [ ]:
alt.Chart(df_grafica).mark_point(filled=True).encode(
    alt.X('apertur'),
    alt.Y('magnitude'),
    color = 'filtro',
    tooltip = 'number',
)

In [ ]:
base = alt.Chart(df_grafica).transform_calculate(
    ymin="datum.y-datum.error_mag",
    ymax="datum.y+datum.error_mag"
)

points = base.mark_point(
    filled=True,
    size=50,
    color='filtro'
).encode(
    x=alt.X('apertur', scale=alt.Scale(domain=(0, 6))),
    y=alt.Y('magnitude', scale=alt.Scale(domain=(10, 11)))
)


errorbars = base.mark_errorbar().encode(
    x = "apertur",
    y = "magnitude",
    y2 = "error_mag"
)

points + errorbars